### ISSUE TITLE
ConfigMap not parsed properly

### ISSUE THREAD

**Issue by sfright** [jenkinsci/kubernetes-cd-plugin#60] opened 2018-07-28 00:59 UTC
Been having alot of issues with getting ConfigMap configuration files to deploy properly - 

```
apiVersion: v1
data:
  certificate.pem: |-
    -----BEGIN CERTIFICATE-----
		MIIDiDCCAvdsvcxstr43DFqdhDANBgkqhkiG9w0BAQsFADCBhTELMAkGA1UEBhMC
		Q0ExEDAOBgNVBAgTB09udGFyaW8xEDAOBgNVBAcTB1Rvcm9udG8xDjAMBgNVBAoT
		BVRFTFVTMRwwGgYDVQQLExNUZWNobm9sb2d5IFN0cmF0ZWd55eQwIgYDVQQDExt0
		ZWx1c2lkZW50aXR5LXJuZC50Zdfact3csa4ty44NMTYwNzI3MDUzOTE2WhcNMjYw
		NzI1MDUzOTE2WjCBhTELMAkGA1/EBhMCQ0ExEDAOBgNVBAgTB09udGFyaW8xEDAO
		BgNVBAcTB1Rvcm9udG8xDjAMBgNVBAoTBVRFTFVTMRwwGgYDVQQLExNUZWNobm9s
		b2d5IFN0cmF0ZWd5MSQwIgYDVQQDExt0ZWx1c2lkZW50aXR5LXJuZC50ZWx1cy5j
		b20wgdawe3favdsfSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCzb4yp8y3B1I03r+2e
		nNwN9+IFcy4xKa75MPu/E3gvP7lnnBC7/aLu1N8EgbPknMd6QIN2uhCQj65r2rnf
		awgUyEBQuWLgglMPgyVpfxCb/JIusY9LD8rSyus6Th+kbhZRORY/ykqhu6Py1u4S
		ic9IwlOKKFDiPXCM+RqMh3Du4NROJ00rzr+lphIXjo2/2IyqL2zdbt+bjni2DTzQ
		fC0IHIMX64ImMP9IgLQoQcxFtV8FzsyNUnblDcxsg533dsfdsg53cyKrtdIiz9vn
		XCB2bRVq1n9/3wkv1CRhrGFzKX5m+03Ohj0aZeyKDqfvMDBua5NfE8EEce9wOExC
		P8hJAgMBAAEasce2wdfsavcNAQELBQADggEBACoP5/xsKmN5OG3u97sUJa1vwIBT
		GzBQH/8AIoECMQcQy6eut9xkDO8FlHF9XZ1SA/BsRCX9WxRtBS5PvvjIv38MlXsl
		mhXP8uAaI/4efOdR6PTPySCi8y/NZ3oTjZBQ5VYwdtDZ4pDkyl7A/Xi2Phi4RIY4
		M90UfSkQvPbBMvcCqKRMBmVOQ3nvm7ZUetI4wDhCakb2JA/66EMJVdo3xpDtXM+H
		0/miytWYUKhNgOeWU9P2OgA4hO0SAtBNKEhRWq04cTciQzN1e0OjbAvhCelsFXVy
		x+ppL2pjttMPpSTMsVrkXe+/4SgWVH/Kgl/ktMc1z7JX3ZEJUdosvuADSh0=
		-----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: examplepem
```
I am able to apply it to my cluster by running without issue running $ kubectl apply -f configmap.yaml w

However as part of my CD flow i receive a parsing error in the job output

```
ERROR: ERROR: java.lang.ClassCastException: com.fasterxml.jackson.databind.node.TextNode cannot be cast to com.fasterxml.jackson.databind.node.ObjectNode
hudson.remoting.ProxyException: java.lang.ClassCastException: com.fasterxml.jackson.databind.node.TextNode cannot be cast to com.fasterxml.jackson.databind.node.ObjectNode
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:50)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:31)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1578)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1166)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:129)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:93)
	at io.fabric8.kubernetes.client.utils.Serialization.getKubernetesResourceList(Serialization.java:248)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:91)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.<init>(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:184)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.<init>(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:170)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient$1.<init>(DefaultKubernetesClient.java:84)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.load(DefaultKubernetesClient.java:84)
	at com.microsoft.jenkins.kubernetes.KubernetesClientWrapper.apply(KubernetesClientWrapper.java:137)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.doCall(DeploymentCommand.java:168)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.call(DeploymentCommand.java:122)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.call(DeploymentCommand.java:105)
	at hudson.FilePath.act(FilePath.java:1129)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:67)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:46)
	at com.microsoft.jenkins.azurecommons.command.CommandService.runCommand(CommandService.java:88)
	at com.microsoft.jenkins.azurecommons.command.CommandService.execute(CommandService.java:96)
	at com.microsoft.jenkins.azurecommons.command.CommandService.executeCommands(CommandService.java:75)
	at com.microsoft.jenkins.azurecommons.command.BaseCommandContext.executeCommands(BaseCommandContext.java:77)
	at com.microsoft.jenkins.kubernetes.KubernetesDeploy.perform(KubernetesDeploy.java:42)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1798)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
ERROR: Kubernetes deployment ended with HasError
```

**Comment by gavinfish** [comment] 2018-09-11 10:00
Seems a duplicate of #51, closing

**Closed by gavinfish** 2018-09-11 10:00 UTC
